version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  mongo:
    image: "mongo:latest"
    ports:
      - 27017:27017
  web:
    image: "blaze:latest"
    network_mode: host
    ports:
      - 8080:8080